name: CD_Pipeline

on:
  workflow_run:
    workflows: [ "ci_pipeline_2" ]
    types: 
      - completed
jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull docker image
      run: sudo docker pull gkm05/ci_cd_pipeline_image:latest
    - name: delete old container if it exists
      run: sudo docker rm -f iris_container || true
    - name: run new container
      run: sudo docker run -d -p 3001:8501 --name iris_container gkm05/ci_cd_pipeline_image:latest 
